### ISSUE TITLE
Error Contents: not well-formed (invalid token)

### ISSUE THREAD

**Issue by strk** [nightflyer73/plugin.video.la7ondemand#3] opened 2014-03-04 18:49 UTC
I've just updated XBMC to 12.2 and plugin.video.la7ondemand to 1.0.2 (5bb2adcc72cff6f94071655c7651dcca07d7cac2) and I'm now getting this error in the xbmc.log when I click on "LA SETTIMANA":

```
19:46:15 T:2750294896  NOTICE: -->Python Interpreter Initialized<--
19:46:16 T:2750294896   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xml.parsers.expat.ExpatError'>
                                            Error Contents: not well-formed (invalid token): line 159, column 61
                                            Traceback (most recent call last):
                                              File "/home/pepperlight/.xbmc/addons/plugin.video.la7ondemand/default.py", line 113, in <module>
                                                show_last_week()
                                              File "/home/pepperlight/.xbmc/addons/plugin.video.la7ondemand/default.py", line 49, in show_last_week
                                                grid = ond.getGrid(ond.EPG)
                                              File "/home/pepperlight/.xbmc/addons/plugin.video.la7ondemand/resources/lib/libLa7.py", line 24, in getGrid
                                                dom = minidom.parseString(xmldata)
                                              File "/usr/lib/python2.6/xml/dom/minidom.py", line 1928, in parseString
                                                return expatbuilder.parseString(string)
                                              File "/usr/lib/python2.6/xml/dom/expatbuilder.py", line 940, in parseString
                                                return builder.parseString(string)
                                              File "/usr/lib/python2.6/xml/dom/expatbuilder.py", line 223, in parseString
                                                parser.Parse(string, True)
                                            ExpatError: not well-formed (invalid token): line 159, column 61
                                            -->End of Python script error report<--
19:46:16 T:3078473520   ERROR: GetDirectory - Error getting plugin://plugin.video.la7ondemand/?mode=epg
```

**Comment by nightflyer73** [comment] 2014-03-05 08:27
This service has been shut down. Even la7 page on cubovision is not updated. This addon will no longer works.

Duplicate of issue #2

**Closed as completed by nightflyer73** 2014-03-05 08:27 UTC
